name: Build

on:
  push:
    branches:
    - main
    paths:
    - 'VERSION'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Sync Repo to the Server
      uses: actions/checkout@v1

    - name: Compile 64bit Binary
      run: gcc .\src\hide_lolbins.c -o .\output\hide_lolbins_x64.exe -s -m64 -lntdll

    - name: Remove Placeholder
      run: Remove-Item output/.gitkeep

    - name: Read Version
      run: |
        $version = Get-Content VERSION
        Write-Output "VERSION=$version" >> $env:GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Hide-LOLBins ${{ env.VERSION }}
        make_latest: true
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        files: ./output/*
